services:
  vue_app:
    container_name: vue_app_container
    build:
      context: .
      dockerfile: containers/app/Dockerfile.dev
    ports:
      - "${VUE_APP_PORT}:${VUE_APP_PORT}"
    environment:
      - "PORT=${VUE_APP_PORT}"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - nest_api
  nest_api:
    container_name: nest_api_container
    build:
      context: .
      dockerfile: containers/api/Dockerfile.dev
    environment:
      - "PORT=${NEST_API_PORT}"
      - "NODE_ENV=${NODE_ENV}"
    ports:
      - "${NEST_API_PORT}:${NEST_API_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
    volumes:
      - ./api:/app
      - /app/node_modules
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: elestio/minio
    container_name: minio_storage
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
volumes:
  pgdata:
  miniodata: