FROM node:22-alpine

WORKDIR /app

RUN npm install -g @quasar/cli

COPY app/package*.json ./
COPY app/ .

RUN npm install

ENV PORT=8080

EXPOSE ${PORT}

CMD ["sh", "-c", "quasar dev -m spa --port ${PORT} --address 0.0.0.0"]