FROM node:22-alpine

WORKDIR /app

RUN npm install -g @nestjs/cli

COPY api/package*.json ./

RUN npm install

ENV PORT=3000
EXPOSE ${PORT}

# Start NestJS in watch mode
CMD ["npm", "run", "start:dev"]